# Generated by Django 4.2.30 on 2026-05-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel / Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.company')),
            ],
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='emissions.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='emissions.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('raw_data', models.JSONField()),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('scope', models.CharField(choices=[('SCOPE1', 'Scope 1 — Direct (fuel combustion)'), ('SCOPE2', 'Scope 2 — Indirect (purchased electricity)'), ('SCOPE3', 'Scope 3 — Value chain (travel, supply chain)')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.company')),
                ('raw_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.rawupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'File Uploaded'), ('APPROVE', 'Record Approved'), ('REJECT', 'Record Rejected'), ('EDIT', 'Record Edited'), ('FLAG', 'Record Flagged as Suspicious')], max_length=20)),
                ('performed_by', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.company')),
                ('raw_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='emissions.rawupload')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='emissions.normalizedemissionrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
